name: CI

on:
  push:
    branches: [master, release]
    tags: [v*.*, v*.*.*]

jobs:
  dockerhub_deploy:
    name: Build latest image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/neuro-inc/docker-registry-frontend
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Build release image
        run: |
          docker build -t $IMAGE_NAME .
      - name: Login to ghcr.io
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push latest image
        id: push
        run: |
          docker push $IMAGE_NAME

  release:
    name: Release image
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/neuro-inc/docker-registry-frontend
      RELEASE_TAG: pipelines
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Build release image
        run: |
          docker build -t $IMAGE_NAME .
      - name: Login to ghcr.io
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push release image
        id: push
        run: |
          set -x
          for tag in $(echo "$RELEASE_TAG,${GITHUB_REF#refs/tags/}" | tr "," " ")
          do
            docker tag $IMAGE_NAME $IMAGE_NAME:$tag && docker push $IMAGE_NAME:$tag
          done
