name: "CI"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  pull_request_target:
    branches: [master]


jobs:
  lint:
    if: |
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]') ||
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]')
    name: Linter
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - name: Checkout commit
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Setup Python 3.8
      uses: actions/setup-python@v4.1.0
      with:
        python-version: '3.8'
    - name: Cache PyPI
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-py-3.8-${{ hashFiles('requirements/*.txt') }}
        path: ${{ env.pythonLocation }}

    - name: Cache pre-commit hooks
      uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-python-3.8-${{ hashFiles('.pre-commit-config.yaml')
          }}

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        make setup
    - name: Run linters
      run: |
        make lint
